---
clickhouse:
  hosts:
    ubuntu-1:
      ansible_host: 89.169.147.72
      ansible_user: ubuntu
  vars:
    clickhouse_version: 24.3.3.102
    clickhouse_packages:
      - clickhouse-common-static
      - clickhouse-client
      - clickhouse-server
vector:
  hosts:
    ubuntu-2:
      ansible_host: 62.84.115.133
      ansible_user: ubuntu
  vars:
    vector_version: 0.47.0
    vector_url_deb: "https://packages.timber.io/vector/0.47.X/vector_0.47.0-1_amd64.deb"
lighthouse:
  hosts:
    ubuntu-3:
      ansible_host: 89.169.154.215
      ansible_user: ubuntu
  vars:
    lighthouse_vcs: https://github.com/VKCOM/lighthouse.git
    lighthouse_location_dir: /var/www/lighthouse
